// NFTLox Protocol - Public API
// v0.2.1 - Tags + Data + SetData

// ============ CONSTANTS ============
export {
	PROTOCOL_ID,
	PROTOCOL_VERSION,
	MIN_PROTOCOL_VERSION,
	HASH_VERSION,
	MAX_JSON_SIZE,
	MAX_OPERATIONS_PER_TX,
	TX_DELAY_MS,
	MAX_NAME_LENGTH,
	MAX_DESCRIPTION_LENGTH,
	MAX_IMAGE_URL_LENGTH,
	MIN_SYMBOL_LENGTH,
	MAX_SYMBOL_LENGTH,
	SYMBOL_REGEX,
	MAX_TAGS,
	MAX_TAG_LENGTH,
	TAG_REGEX,
	ORIGIN_DNA_LENGTH,
	INSTANCE_DNA_LENGTH,
	ACCESS_KEY_LENGTH,
	SUPPORTED_CURRENCIES,
	MAX_ROYALTY_PCT,
	MIN_PRICE_AMOUNT,
	ACTION_CREATE_COLLECTION,
	ACTION_MINT,
	ACTION_TRANSFER,
	ACTION_BURN,
	ACTION_REPLICATE,
	ACTION_DISTRIBUTE,
	ACTION_SET_DATA,
	ACTION_LIST,
	ACTION_UNLIST,
	ACTION_BUY,
	ACTION_OFFER,
	ACTION_ACCEPT_OFFER,
	ACTION_REJECT_OFFER,
	ACTION_PACK_CREATE,
	ACTION_PACK_BUY,
	ACTION_PACK_TRANSFER,
	ACTION_PACK_OPEN,
	ACTION_PACK_APPROVE,
	ACTION_PACK_TRANSFER_FROM,
	ACTION_NFT_APPROVE,
	ACTION_NFT_APPROVE_ALL,
	ACTION_NFT_TRANSFER_FROM,
	ACTION_NFT_LEND,
	ACTION_NFT_RETURN,
	ACTION_DATA_OPERATOR_APPROVE,
	ACTION_SET_DATA_FROM,
	CORE_ACTIONS,
	MARKETPLACE_ACTIONS,
	PACK_ACTIONS,
	APPROVE_ACTIONS,
	LENDING_ACTIONS,
	DATA_OPERATOR_ACTIONS,
	ALL_ACTIONS,
	MAX_DROP_TABLE_ENTRIES,
	MAX_ITEMS_PER_PACK,
	MAX_PACK_OPEN_BATCH,
	MIN_DROP_WEIGHT,
	MAX_DROP_WEIGHT,
	type CoreAction,
	type MarketplaceAction,
	type PackAction,
	type ApproveAction,
	type LendingAction,
	type DataOperatorAction,
	type ProtocolAction,
	type SupportedCurrency,
} from "./constants";

// ============ TYPES ============
export type {
	HiveOperation,
	Price,
	CollectionMetadata,
	CollectionRules,
	CollectionData,
	NFTMetadata,
	NFTData,
	ReplicaData,
	DistributeData,
	DistributeInput,
	TransferData,
	BurnData,
	SetDataData,
	SetDataInput,
	DataOperatorApproveData,
	DataOperatorApproveInput,
	SetDataFromData,
	SetDataFromInput,
	ListingData,
	UnlistData,
	BuyData,
	OfferData,
	AcceptOfferData,
	RejectOfferData,
	HistoryEventType,
	HistoryEvent,
	ProtocolPayload,
	CreateCollectionInput,
	MintInput,
	ReplicateInput,
	ListInput,
	BuyInput,
	BurnInput,
	UnlistInput,
	OfferInput,
	AcceptOfferInput,
	RejectOfferInput,
	ImportedNFT,
	TransferMemoAction,
	TransferMemo,
	AtomicTransferInput,
	HiveTransferOperation,
	AtomicOperation,
	OwnershipRecord,
	// Anti-duplication types
	SeedNFTWithArtId,
	PreMintValidationResult,
	MintingSession,
	// Pack types
	PackDropEntry,
	PackCreateData,
	PackBuyData,
	PackTransferData,
	PackOpenData,
	PackCreateInput,
	PackBuyInput,
	PackTransferInput,
	PackOpenInput,
	// Approve & TransferFrom types
	PackApproveData,
	PackApproveInput,
	PackTransferFromData,
	PackTransferFromInput,
	NftApproveData,
	NftApproveInput,
	NftApproveAllData,
	NftApproveAllInput,
	NftTransferFromData,
	NftTransferFromInput,
	// Lending types
	NftLendData,
	NftLendInput,
	NftReturnData,
	NftReturnInput,
} from "./types";

// ============ DNA GENERATION ============
export {
	generateHashAsync,
	generateHashSync,
	generateOriginDna,
	generateOriginDnaSync,
	generateInstanceDna,
	generateReplicaInstanceDna,
	generateAccessKey,
	generateImageHash,
	generateId,
	generateReplicaId,
	extractOriginalId,
	isReplicaId,
	generateOfferId,
	// Seed & Instance helpers
	generateSeedId,
	generateInstanceId,
	extractSeedId,
	extractInstanceNumber,
	isSeedId,
	isInstanceId,
	// ArtId validation
	validateArtId,
	validateArtIdArray,
	type ArtIdValidationResult,
	// Deterministic ID generation (anti-duplication)
	deterministicHash,
	generateDeterministicCollectionId,
	generateDeterministicSeedId,
	generateDeterministicInstanceId,
	// Pack ID & RNG
	generateDeterministicPackId,
	isPackId,
	generateDeterministicInstanceDna,
	generateDeterministicAccessKey,
	deterministicRng,
	resolveDropTable,
} from "./dna";

// ============ PAYLOAD CREATION ============
export {
	// Payload creators
	createCollectionPayload,
	createMintPayload,
	createReplicatePayload,
	createDistributePayload,
	createTransferPayload,
	createBurnPayload,
	createSetDataPayload,
	createDataOperatorApprovePayload,
	createDataOperatorApproveOperation,
	createSetDataFromPayload,
	createSetDataFromOperation,
	sanitizeTags,
	createListPayload,
	createUnlistPayload,
	createBuyPayload,
	createOfferPayload,
	createAcceptOfferPayload,
	createRejectOfferPayload,
	// Operation creators
	createCollectionOperation,
	createMintOperation,
	createReplicateOperation,
	createDistributeOperation,
	createTransferOperation,
	createBurnOperation,
	createSetDataOperation,
	createListOperation,
	createUnlistOperation,
	createBuyOperation,
	createOfferOperation,
	createAcceptOfferOperation,
	createRejectOfferOperation,
	// Atomic transfer (dual-registro)
	buildTransferMemo,
	parseTransferMemo,
	createAtomicTransferOperations,
	getTrackingAmount,
	// Deterministic payload creation (anti-duplication)
	createDeterministicCollectionPayload,
	createDeterministicMintPayload,
	createDeterministicDistributePayload,
	type DeterministicCollectionInput,
	type DeterministicMintInput,
	// Pack payloads & operations
	createPackCreatePayload,
	createPackBuyPayload,
	createPackTransferPayload,
	createPackOpenPayload,
	createPackCreateOperation,
	createPackBuyOperation,
	createPackTransferOperation,
	createPackOpenOperation,
	// Approve & TransferFrom payloads & operations
	createPackApprovePayload,
	createPackApproveOperation,
	createPackTransferFromPayload,
	createPackTransferFromOperation,
	createNftApprovePayload,
	createNftApproveOperation,
	createNftApproveAllPayload,
	createNftApproveAllOperation,
	createNftTransferFromPayload,
	createNftTransferFromOperation,
	// Lending payloads & operations
	createNftLendPayload,
	createNftLendOperation,
	createNftReturnPayload,
	createNftReturnOperation,
} from "./payloads";

// ============ VALIDATION ============
export {
	type ValidationResult,
	validateSymbol,
	normalizeSymbol,
	validatePrice,
	validateCollectionInput,
	validateMintInput,
	validateListInput,
	validateOfferInput,
	validateImportedNFTs,
	estimateOperationSize,
	validateOperationSize,
	splitIntoBatches,
	calculateMaxOperationsPerTx,
	validatePackCreateInput,
	validatePackBuyInput,
	validatePackTransferInput,
	validatePackOpenInput,
	validatePackApproveInput,
	validatePackTransferFromInput,
	validateNftApproveInput,
	validateNftApproveAllInput,
	validateNftTransferFromInput,
	validateDataOperatorApproveInput,
	validateSetDataFromInput,
	validateNftLendInput,
	validateNftReturnInput,
} from "./validation";

// ============ PAYLOAD BUILDER ============
export {
	PayloadBuilder,
	payloadBuilder,
	type ValidationError,
	type BuildResult,
	type SeedInput,
	type SeedBatchInput,
	type SeedBatchPayload,
} from "./payload-builder";

// ============ SPV VERIFICATION ============
export {
	// Types
	type HiveL1Config,
	type HafahTransaction,
	type L1ParsedOperation,
	type VerificationStatus,
	type SpvMismatch,
	type ReportedMintedNft,
	type PackOpenVerificationResult,
	type OnChainVerificationResult,
	type OwnershipVerifyParams,
	type OwnershipVerificationResult,
	type OwnershipCheckResult,
	type AuditorConfig,
	type AuditReport,
	type DropTableReplayParams,
	type DeterministicDerivationParams,
	type DeterministicDerivationResult,
	type PackOpenVerifyParams,
	type OnChainVerifyParams,
	// Constants
	DEFAULT_HIVE_ENDPOINTS,
	DEFAULT_HIVE_TIMEOUT_MS,
	DEFAULT_AUDIT_SAMPLE_SIZE,
	buildRngSeed,
	// L1 Client
	HiveRpcError,
	createDefaultL1Config,
	fetchTransaction,
	fetchFromHiveRpc,
	parseNftloxOperation,
	// Verifiers
	replayDropTableResolution,
	verifyDeterministicDerivation,
	verifyPackOpen,
	verifyOperationOnChain,
	verifyNftOwnership,
	// Auditor
	createAuditorConfig,
	fetchRecentPackOpenEvents,
	runAudit,
	runSingleVerification,
} from "./spv";
