// NFTLox Protocol - Public API
// v0.2.1 - Tags + Data + SetData

// ============ CONSTANTS ============
export {
	PROTOCOL_ID,
	PROTOCOL_VERSION,
	MIN_PROTOCOL_VERSION,
	HASH_VERSION,
	MAX_JSON_SIZE,
	MAX_OPERATIONS_PER_TX,
	TX_DELAY_MS,
	MAX_NAME_LENGTH,
	MAX_DESCRIPTION_LENGTH,
	MAX_IMAGE_URL_LENGTH,
	MIN_SYMBOL_LENGTH,
	MAX_SYMBOL_LENGTH,
	SYMBOL_REGEX,
	MAX_TAGS,
	MAX_TAG_LENGTH,
	TAG_REGEX,
	ORIGIN_DNA_LENGTH,
	INSTANCE_DNA_LENGTH,
	ACCESS_KEY_LENGTH,
	SUPPORTED_CURRENCIES,
	MAX_ROYALTY_PCT,
	MIN_PRICE_AMOUNT,
	ACTION_CREATE_COLLECTION,
	ACTION_MINT,
	ACTION_TRANSFER,
	ACTION_BURN,
	ACTION_REPLICATE,
	ACTION_DISTRIBUTE,
	ACTION_SET_DATA,
	ACTION_LIST,
	ACTION_UNLIST,
	ACTION_BUY,
	ACTION_OFFER,
	ACTION_ACCEPT_OFFER,
	ACTION_REJECT_OFFER,
	CORE_ACTIONS,
	MARKETPLACE_ACTIONS,
	ALL_ACTIONS,
	type CoreAction,
	type MarketplaceAction,
	type ProtocolAction,
	type SupportedCurrency,
} from "./constants";

// ============ TYPES ============
export type {
	HiveOperation,
	Price,
	CollectionMetadata,
	CollectionRules,
	CollectionData,
	NFTMetadata,
	NFTData,
	ReplicaData,
	DistributeData,
	DistributeInput,
	TransferData,
	BurnData,
	SetDataData,
	SetDataInput,
	ListingData,
	UnlistData,
	BuyData,
	OfferData,
	AcceptOfferData,
	RejectOfferData,
	HistoryEventType,
	HistoryEvent,
	ProtocolPayload,
	CreateCollectionInput,
	MintInput,
	ReplicateInput,
	ListInput,
	BuyInput,
	BurnInput,
	UnlistInput,
	OfferInput,
	AcceptOfferInput,
	RejectOfferInput,
	ImportedNFT,
	TransferMemoAction,
	TransferMemo,
	AtomicTransferInput,
	HiveTransferOperation,
	AtomicOperation,
	OwnershipRecord,
	// Anti-duplication types
	SeedNFTWithArtId,
	PreMintValidationResult,
	MintingSession,
} from "./types";

// ============ DNA GENERATION ============
export {
	generateHashAsync,
	generateHashSync,
	generateOriginDna,
	generateOriginDnaSync,
	generateInstanceDna,
	generateReplicaInstanceDna,
	generateAccessKey,
	generateImageHash,
	generateId,
	generateReplicaId,
	extractOriginalId,
	isReplicaId,
	generateOfferId,
	// Seed & Instance helpers
	generateSeedId,
	generateInstanceId,
	extractSeedId,
	extractInstanceNumber,
	isSeedId,
	isInstanceId,
	// ArtId validation
	validateArtId,
	validateArtIdArray,
	type ArtIdValidationResult,
	// Deterministic ID generation (anti-duplication)
	deterministicHash,
	generateDeterministicCollectionId,
	generateDeterministicSeedId,
	generateDeterministicInstanceId,
} from "./dna";

// ============ PAYLOAD CREATION ============
export {
	// Payload creators
	createCollectionPayload,
	createMintPayload,
	createReplicatePayload,
	createDistributePayload,
	createTransferPayload,
	createBurnPayload,
	createSetDataPayload,
	sanitizeTags,
	createListPayload,
	createUnlistPayload,
	createBuyPayload,
	createOfferPayload,
	createAcceptOfferPayload,
	createRejectOfferPayload,
	// Operation creators
	createCollectionOperation,
	createMintOperation,
	createReplicateOperation,
	createDistributeOperation,
	createTransferOperation,
	createBurnOperation,
	createSetDataOperation,
	createListOperation,
	createUnlistOperation,
	createBuyOperation,
	createOfferOperation,
	createAcceptOfferOperation,
	createRejectOfferOperation,
	// Atomic transfer (dual-registro)
	buildTransferMemo,
	parseTransferMemo,
	createAtomicTransferOperations,
	getTrackingAmount,
	// Deterministic payload creation (anti-duplication)
	createDeterministicCollectionPayload,
	createDeterministicMintPayload,
	createDeterministicDistributePayload,
	type DeterministicCollectionInput,
	type DeterministicMintInput,
} from "./payloads";

// ============ VALIDATION ============
export {
	type ValidationResult,
	validateSymbol,
	normalizeSymbol,
	validatePrice,
	validateCollectionInput,
	validateMintInput,
	validateListInput,
	validateOfferInput,
	validateImportedNFTs,
	estimateOperationSize,
	validateOperationSize,
	splitIntoBatches,
	calculateMaxOperationsPerTx,
} from "./validation";

// ============ PAYLOAD BUILDER ============
export {
	PayloadBuilder,
	payloadBuilder,
	type ValidationError,
	type BuildResult,
	type SeedInput,
	type SeedBatchInput,
	type SeedBatchPayload,
} from "./payload-builder";
