// NFTLox Protocol - Public API
// v0.3.0 - Typed Schemas + Data Tracking

// ============ CONSTANTS ============
export {
	PROTOCOL_ID,
	PROTOCOL_VERSION,
	MIN_PROTOCOL_VERSION,
	HASH_VERSION,
	MAX_JSON_SIZE,
	MAX_OPERATIONS_PER_TX,
	TX_DELAY_MS,
	MAX_NAME_LENGTH,
	MAX_DESCRIPTION_LENGTH,
	MAX_IMAGE_URL_LENGTH,
	MIN_SYMBOL_LENGTH,
	MAX_SYMBOL_LENGTH,
	SYMBOL_REGEX,
	ORIGIN_DNA_LENGTH,
	INSTANCE_DNA_LENGTH,
	ACCESS_KEY_LENGTH,
	INSTANCE_ID_HASH_LENGTH,
	SUPPORTED_CURRENCIES,
	MAX_ROYALTY_PCT,
	MIN_PRICE_AMOUNT,
	PROTOCOL_FEE_PCT,
	DEFAULT_FEE_ACCOUNT,
	calculatePaymentSplit,
	roundHive,
	type PaymentSplit,
	HIVE_CUSTOM_JSON_MAX_BYTES,
	SAFE_PAYLOAD_MAX_BYTES,
	ACTION_CREATE_COLLECTION,
	ACTION_MINT,
	ACTION_TRANSFER,
	ACTION_BURN,
	ACTION_REPLICATE,
	ACTION_BULK_DISTRIBUTE,
	MAX_BULK_DISTRIBUTE_ITEMS,
	ACTION_SET_DATA,
	ACTION_SET_OWNER_DATA,
	ACTION_EXTEND_SCHEMA,
	ACTION_ARCHIVE_COLLECTION,
	MAX_SCHEMA_FIELDS,
	MAX_FIELD_NAME_LENGTH,
	ACTION_LIST,
	ACTION_UNLIST,
	ACTION_BUY,
	ATOMIC_TRACKING_AMOUNT,
	LISTING_ID_PREFIX,
	LISTING_NONCE_LENGTH,
	LISTING_HASH_LENGTH,
	MEMO_PREFIX_BUY,
	MEMO_PREFIX_ROYALTY,
	MEMO_PREFIX_FEE,
	MULTISIG_EXPIRATION_MS,
	MAX_MULTISIG_OPERATIONS,
	ACTION_PACK_CREATE,
	ACTION_PACK_BUY,
	ACTION_PACK_TRANSFER,
	ACTION_PACK_OPEN,
	ACTION_PACK_APPROVE,
	ACTION_PACK_TRANSFER_FROM,
	ACTION_NFT_APPROVE,
	ACTION_NFT_APPROVE_ALL,
	ACTION_NFT_TRANSFER_FROM,
	ACTION_NFT_LEND,
	ACTION_NFT_RETURN,
	ACTION_DATA_OPERATOR_APPROVE,
	ACTION_SET_DATA_FROM,
	CORE_ACTIONS,
	MARKETPLACE_ACTIONS,
	PACK_ACTIONS,
	APPROVE_ACTIONS,
	LENDING_ACTIONS,
	DATA_OPERATOR_ACTIONS,
	ALL_ACTIONS,
	ACTIVE_AUTH_ACTIONS,
	POSTING_AUTH_ACTIONS,
	type ActiveAuthAction,
	type PostingAuthAction,
	MAX_DROP_TABLE_ENTRIES,
	MAX_ITEMS_PER_PACK,
	MAX_PACK_OPEN_BATCH,
	MIN_DROP_WEIGHT,
	MAX_DROP_WEIGHT,
	type CoreAction,
	type MarketplaceAction,
	type PackAction,
	type ApproveAction,
	type LendingAction,
	type DataOperatorAction,
	type ProtocolAction,
	type SupportedCurrency,
} from "./constants";

// ============ TYPES ============
export type {
	// Schema types
	SchemaFieldType,
	SchemaField,
	CollectionSchema,
	ExtendSchemaData,
	SetOwnerDataData,
	DataProof,
	// Core types
	HiveOperation,
	Price,
	CollectionMetadata,
	CollectionRules,
	CollectionData,
	ArchiveCollectionData,
	NFTMetadata,
	NFTData,
	SeedProvenance,
	ReplicaData,
	BulkDistributeItem,
	BulkDistributeData,
	BulkDistributeInput,
	TransferData,
	BurnData,
	SetDataData,
	SetDataInput,
	DataOperatorApproveData,
	DataOperatorApproveInput,
	SetDataFromData,
	SetDataFromInput,
	ListingData,
	UnlistData,
	BuyData,
	HiveTransactionObject,
	MultisigErrorCode,
	MultisigResponse,
	MultisigRequest,
	PaymentInfo,
	ProtocolPayload,
	CreateCollectionInput,
	ArchiveCollectionInput,
	MintInput,
	ReplicateInput,
	ListInput,
	BuyInput,
	BurnInput,
	UnlistInput,
	ImportedNFT,
	TransferMemoAction,
	TransferMemo,
	AtomicTransferInput,
	HiveTransferOperation,
	AtomicOperation,
	// Anti-duplication types
	SeedNFTWithArtId,
	PreMintValidationResult,
	MintingSession,
	// Pack types
	PackDropEntry,
	PackCreateData,
	PackBuyData,
	PackTransferData,
	PackOpenData,
	PackCreateInput,
	PackBuyInput,
	PackTransferInput,
	PackOpenInput,
	// Approve & TransferFrom types
	PackApproveData,
	PackApproveInput,
	PackTransferFromData,
	PackTransferFromInput,
	NftApproveData,
	NftApproveInput,
	NftApproveAllData,
	NftApproveAllInput,
	NftTransferFromData,
	NftTransferFromInput,
	// Lending types
	NftLendData,
	NftLendInput,
	NftReturnData,
	NftReturnInput,
} from "./types";

// ============ DNA GENERATION ============
export {
	generateHash,
	generateOriginDna,
	generateInstanceDna,
	generateReplicaInstanceDna,
	generateAccessKey,
	generateImageHash,
	generateReplicaId,
	extractOriginalId,
	isReplicaId,
	// Seed & Instance helpers
	generateInstanceId,
	extractSeedId,
	extractInstanceNumber,
	isSeedId,
	isInstanceId,
	// ArtId validation
	validateArtId,
	validateArtIdArray,
	type ArtIdValidationResult,
	// Deterministic ID generation (SHA-256)
	generateDeterministicCollectionId,
	generateDeterministicSeedId,
	generateDeterministicInstanceId,
	// Listing ID
	generateListingNonce,
	generateListingId,
	// Pack ID & RNG
	generateDeterministicPackId,
	isPackId,
	generateDeterministicInstanceDna,
	generateDeterministicAccessKey,
	deterministicRng,
	resolveDropTable,
} from "./dna";

// ============ PAYLOAD CREATION ============
export {
	// Payload creators
	createReplicatePayload,
	createBulkDistributePayload,
	createBulkDistributeOperation,
	createTransferPayload,
	createBurnPayload,
	createSetDataPayload,
	createDataOperatorApprovePayload,
	createDataOperatorApproveOperation,
	createSetDataFromPayload,
	createSetDataFromOperation,
	createSetOwnerDataPayload,
	createSetOwnerDataOperation,
	createExtendSchemaPayload,
	createExtendSchemaOperation,
	createArchiveCollectionPayload,
	createArchiveCollectionOperation,
	createListPayload,
	createUnlistPayload,
	createBuyPayload,
	createBuyOperation,
	// Operation creators
	createReplicateOperation,
	createTransferOperation,
	createBurnOperation,
	createSetDataOperation,
	createListOperation,
	createUnlistOperation,
	// Atomic transfer (dual-registro)
	buildTransferMemo,
	parseTransferMemo,
	createAtomicTransferOperations,
	getTrackingAmount,
	// Deterministic payload & operation creation (anti-duplication)
	createDeterministicCollectionPayload,
	createDeterministicCollectionOperation,
	createDeterministicMintPayload,
	createDeterministicMintOperation,
	toHiveOperation,
	type DeterministicCollectionInput,
	type DeterministicMintInput,
	// Pack payloads & operations
	createPackCreatePayload,
	createPackBuyPayload,
	createPackTransferPayload,
	createPackOpenPayload,
	createPackCreateOperation,
	createPackBuyOperation,
	createPackTransferOperation,
	createPackOpenOperation,
	// Approve & TransferFrom payloads & operations
	createPackApprovePayload,
	createPackApproveOperation,
	createPackTransferFromPayload,
	createPackTransferFromOperation,
	createNftApprovePayload,
	createNftApproveOperation,
	createNftApproveAllPayload,
	createNftApproveAllOperation,
	createNftTransferFromPayload,
	createNftTransferFromOperation,
	// Lending payloads & operations
	createNftLendPayload,
	createNftLendOperation,
	createNftReturnPayload,
	createNftReturnOperation,
	PayloadTooLargeError,
} from "./payloads";

// ============ SCHEMAS ============
export * from "./schemas";
export { validateNftOperation } from "./validate";
export type { NftState, PreValidationResult } from "./validate";

// ============ SCHEMA VALIDATION ============
export {
	VALID_SCHEMA_TYPES,
	canonicalJson,
	computeDataHash,
	validateValueAgainstType,
	validateSchemaDefinition,
	validateMintData,
	validateMutableUpdate,
	mergeSchemas,
} from "./schema-validation";

// ============ SCHEMA TEMPLATES ============
export {
	GAMING_SCHEMA,
	ART_SCHEMA,
	COLLECTIBLE_SCHEMA,
	MUSIC_SCHEMA,
	RAGNAROK_MINION_SCHEMA,
	RAGNAROK_SPELL_SCHEMA,
	RAGNAROK_WEAPON_SCHEMA,
	RAGNAROK_PET_SCHEMA,
	RAGNAROK_ARMOR_SCHEMA,
	RAGNAROK_HERO_SCHEMA,
	createSchemaBuilder,
} from "./schema-templates";

// ============ BUILDERS ============
export * from "./builders";

// ============ MULTISIG CLIENT ============
export {
	fetchPaymentInfo,
	requestMultisig,
} from "./multisig";


// ============ SPV VERIFICATION ============
export {
	// Types
	type HiveL1Config,
	type HafahTransaction,
	type L1ParsedOperation,
	type VerificationStatus,
	type SpvMismatch,
	type ReportedMintedNft,
	type PackOpenVerificationResult,
	type OnChainVerificationResult,
	type OwnershipVerifyParams,
	type OwnershipVerificationResult,
	type OwnershipCheckResult,
	type AuditorConfig,
	type AuditReport,
	type DropTableReplayParams,
	type DeterministicDerivationParams,
	type DeterministicDerivationResult,
	type PackOpenVerifyParams,
	type OnChainVerifyParams,
	// Constants
	DEFAULT_HIVE_ENDPOINTS,
	DEFAULT_HIVE_TIMEOUT_MS,
	DEFAULT_AUDIT_SAMPLE_SIZE,
	buildRngSeed,
	// L1 Client
	HiveRpcError,
	createDefaultL1Config,
	fetchTransaction,
	fetchFromHiveRpc,
	parseNftloxOperation,
	// Verifiers
	replayDropTableResolution,
	verifyDeterministicDerivation,
	verifyPackOpen,
	verifyOperationOnChain,
	verifyNftOwnership,
	// Auditor
	createAuditorConfig,
	fetchRecentPackOpenEvents,
	runAudit,
	runSingleVerification,
} from "./spv";

// ============ INDEXER CLIENT ============
export {
	createIndexerClient,
	IndexerError,
	type IndexerClient,
	type SyncStatus,
	type HealthStatus,
	type ProtocolStats,
	type IndexerCollection,
	type CollectionStats,
	type IndexerNft,
	type IndexerNftSummary,
	type IndexerPack,
	type PackBalance,
	type UserNftCounts,
	type UserNftsPage,
} from "./client";

// ============ UTILS ============
export * from "./utils/tx-sizing";
