// Guardrail for the SDK's curated public surface.
//
// nftlox-sdk publishes independently on npm; every symbol re-exported from
// @nftlox/protocol through src/protocol-exports.ts is part of the SDK's semver
// contract. Letting protocol additions leak to the SDK surface silently would
// inflate that contract on every protocol change.
//
// This test pins the set of runtime-value symbols exported by @nftlox/protocol.
// When a protocol change adds/removes a symbol, the test fails with a diff, and
// the developer must:
//   1) Update PROTOCOL_RUNTIME_SURFACE below to match reality.
//   2) Decide whether packages/sdk/src/protocol-exports.ts should re-export the
//      new symbol (integrator-facing? semver-stable?) or keep it internal.
//
// Last review: 2026-05-13.

import { describe, expect, it } from "bun:test";
import * as protocol from "@nftlox/protocol";

const PROTOCOL_RUNTIME_SURFACE: ReadonlyArray<string> = [
	"ACCESS_KEY_LENGTH",
	"ACTION_ARCHIVE_COLLECTION",
	"ACTION_AUTH_LEVEL",
	"ACTION_BULK_DISTRIBUTE",
	"ACTION_BUY",
	"ACTION_BUY_COMMITMENT",
	"ACTION_CREATE_COLLECTION",
	"ACTION_DATA_OPERATOR_APPROVE",
	"ACTION_EXTEND_SCHEMA",
	"ACTION_LIST",
	"ACTION_MINT",
	"ACTION_NFT_APPROVE",
	"ACTION_NFT_APPROVE_ALL",
	"ACTION_NFT_LEND",
	"ACTION_NFT_RETURN",
	"ACTION_NFT_TRANSFER_FROM",
	"ACTION_NODE_HEARTBEAT",
	"ACTION_NODE_REGISTER",
	"ACTION_NODE_STATE_CHECKPOINT",
	"ACTION_PAYMENT",
	"ACTION_SET_DATA",
	"ACTION_SET_DATA_FROM",
	"ACTION_TRANSFER",
	"ACTION_UNLIST",
	"ACTIVE_AUTH_ACTIONS",
	"ALL_ACTIONS",
	"APPROVE_ACTIONS",
	"BASIS_POINTS_DENOMINATOR",
	"BURN_RECIPIENT",
	"BUY_API_HEAD_STALENESS_MAX_MS",
	"BUY_API_LAG_MAX_BLOCKS",
	"BUY_COMMITMENT_OBSERVATION_TIMEOUT_MS",
	"BUY_COMMITMENT_TTL_BLOCKS",
	"BUY_TX_TTL_MS",
	"COLLECTION_ID_HASH_LENGTH",
	"COLLECTION_ID_PREFIX",
	"CORE_ACTIONS",
	"DATA_OPERATOR_ACTIONS",
	"DEFAULT_FEE_ACCOUNT",
	"HASH_DOMAIN_COL",
	"HASH_DOMAIN_DNA",
	"HASH_DOMAIN_IMG",
	"HASH_DOMAIN_KEY",
	"HASH_DOMAIN_LISTING",
	"HASH_DOMAIN_ORIGIN",
	"HASH_DOMAIN_SEED",
	"HASH_DOMAIN_SEED_DNA",
	"HASH_FORMAT_PREFIX",
	"HASH_VERSION",
	"HIVE_AMOUNT_EPSILON",
	"HIVE_BLOCK_TIME_MS",
	"HIVE_CUSTOM_JSON_MAX_BYTES",
	"HIVE_DECIMALS",
	"HIVE_FINALITY_SAFETY_BLOCKS",
	"HIVE_PRECISION",
	"IMAGE_ID_HASH_LENGTH",
	"IMAGE_ID_PREFIX",
	"INSTANCE_DNA_LENGTH",
	"INSTANCE_FEE_ENABLED",
	"INSTANCE_FEE_PER_N",
	"INSTANCE_FEE_UNIT_HBD",
	"INSTANCE_ID_HASH_LENGTH",
	"INSTANCE_ID_PREFIX",
	"LENDING_ACTIONS",
	"LISTING_HASH_LENGTH",
	"LISTING_ID_PREFIX",
	"LISTING_MAX_DURATION_BLOCKS",
	"LISTING_MIN_DURATION_BLOCKS",
	"LISTING_NONCE_LENGTH",
	"MARKETPLACE_ACTIONS",
	"MAX_ACTIVE_COMMITMENTS_PER_NODE",
	"MAX_ART_ID_LENGTH",
	"MAX_BULK_DISTRIBUTE_ITEMS",
	"MAX_BULK_DISTRIBUTE_TOTAL_QUANTITY",
	"MAX_DESCRIPTION_LENGTH",
	"MAX_FIELD_NAME_LENGTH",
	"MAX_ID_LENGTH",
	"MAX_IMAGE_URL_LENGTH",
	"MAX_INSTANCES_PER_COLLECTION",
	"MAX_JSON_SIZE",
	"MAX_MARKETPLACE_LENGTH",
	"MAX_NAME_LENGTH",
	"MAX_NODE_HEARTBEAT_STALENESS_BLOCKS",
	"MAX_OPERATIONS_PER_TX",
	"MAX_ROYALTY_PCT",
	"MAX_SCHEMA_FIELDS",
	"MAX_SYMBOL_LENGTH",
	"MAX_TRANSFER_BATCH_SIZE",
	"MAX_URL_LENGTH",
	"MEMO_PREFIX_BUY",
	"MEMO_PREFIX_FEE",
	"MEMO_PREFIX_FEE_COL",
	"MEMO_PREFIX_ROYALTY",
	"MEMO_TAG_BUY",
	"MEMO_TAG_FEE",
	"MEMO_TAG_FEE_COL",
	"MEMO_TAG_ROYALTY",
	"MIN_HEARTBEAT_INTERVAL_BLOCKS",
	"MAX_LISTING_TTL_MS",
	"MIN_LISTING_TTL_BUFFER_MS",
	"MIN_LISTING_TTL_MS",
	"MIN_PRICE_AMOUNT",
	"MIN_PROTOCOL_VERSION",
	"MIN_SYMBOL_LENGTH",
	"MULTISIG_TX_MAX_EXPIRATION_MS",
	"MULTISIG_TX_MIN_EXPIRATION_MS",
	"NFT_DNA_PREFIX",
	"NODE_SIGNED_ACTIONS",
	"ORIGIN_DNA_LENGTH",
	"ORIGIN_DNA_PREFIX",
	"POSTING_AUTH_ACTIONS",
	"PROTOCOL_COLLECTION_FEE_HBD",
	"PROTOCOL_FEE_BPS",
	"PROTOCOL_GENESIS_BLOCK",
	"PROTOCOL_GENESIS_BLOCK_ID",
	"PROTOCOL_ID",
	"PROTOCOL_VERSION",
	"PROTOCOL_VERSION_REGEX",
	"PayloadTooLargeError",
	"RECOMMENDED_BUY_TX_EXPIRATION_MS",
	"SAFE_PAYLOAD_MAX_BYTES",
	"SEED_ID_PREFIX",
	"STATE_CHECKPOINT_INTERVAL_BLOCKS",
	"SUPPORTED_CURRENCIES",
	"SYMBOL_REGEX",
	"TX_DELAY_MS",
	"TX_ID_REGEX",
	"VALID_SCHEMA_TYPES",
	"assertAcceptedProtocolVersion",
	"assertNeverPaymentKind",
	"assertProvenanceTarget",
	"assertValidProtocolVersion",
	"calculateBasisPointsAmount",
	"calculatePaymentSplit",
	"calculatePaymentSplitFromUnits",
	"canonicalJson",
	"castPayloadByAction",
	"compareVersions",
	"computeDataHash",
	"createHiveOperation",
	"createPayload",
	"extractInstanceNumber",
	"extractSeedId",
	"fromWireUrl",
	"generateDeterministicAccessKey",
	"generateDeterministicCollectionId",
	"generateDeterministicInstanceId",
	"generateDeterministicSeedId",
	"generateHash",
	"generateImageHash",
	"generateInstanceDna",
	"generateInstanceId",
	"generateListingId",
	"generateListingNonce",
	"generateOriginDna",
	"generateSeedDna",
	"getAuthLevel",
	"getAuthMismatchReason",
	"getKeyType",
	"getLimit",
	"getPaymentRequirement",
	"isAcceptedProtocolVersion",
	"isCollectionId",
	"isHiveTxId",
	"isInstanceId",
	"isListingId",
	"isProtocolAction",
	"isSeedId",
	"isSymbol",
	"isValidProtocolVersion",
	"matchProvenance",
	"mergeSchemas",
	"normalizeNodeEndpoint",
	"parseInstanceId",
	"parseProtocolVersion",
	"percentageToBasisPoints",
	"readDeclaredProvenance",
	"requiresActiveNodeSigner",
	"requiresTransferEnrichment",
	"resolvePaymentRecipient",
	"roundHive",
	"toWireUrl",
	"validateGenesisBlockSelection",
	"validateHiveUsername",
	"validateMintData",
	"validateMutableSnapshot",
	"validateMutableUpdate",
	"validateNodeEndpoint",
	"validateSchemaDefinition",
	"validateValueAgainstType",
];

describe("@nftlox/protocol runtime surface", () => {
	it("matches the committed allowlist — review protocol-exports.ts when this fails", () => {
		const actual = Object.keys(protocol).sort();
		const expected = [...PROTOCOL_RUNTIME_SURFACE].sort();
		expect(actual).toEqual(expected);
	});
});
